name: cloudos
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.9
    - pip>=21.2.4
    - requests>=2.26.0
    - click>=8.0.1
    - rich-click>=1.8.2
    - pandas>=1.3.4
    - numpy>=1.26.4
