name: CI_tests

on:
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
      - main
      - dev
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install -e '.[test]'
    - name: Run tests
      run: |
        pytest
  job_list:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      env:
        CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
        CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
        CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
      run: |
        cloudos job list --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --workspace-id $CLOUDOS_WORKSPACE_ID
  job_details:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      env:
        CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
        CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
        CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
      run: |
        JOB_ID="68497c969750c32eba238ce6"
        cloudos job details --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --job-id $JOB_ID
  import_gitlab:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Run tests
        env:
          CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
          CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
          CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          cloudos workflow import --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --workspace-id $CLOUDOS_WORKSPACE_ID --workflow-name imported_from_gitlab --workflow-url https://gitlab.com/lb-ortiz/spammer-nf --repository-platform gitlab
  import_github:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Run tests
        env:
          CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
          CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
          CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          cloudos workflow import --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --workspace-id $CLOUDOS_WORKSPACE_ID --workflow-name imported_from_github --workflow-url https://github.com/lifebit-ai/spammer-nf --repository-platform github
  job_run_and_status:
    runs-on: ubuntu-latest
    outputs:
      job_id: ${{ steps.get-job-id.outputs.job_id }}
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      id: get-job-id
      env:
        CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
        CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
        CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
        PROJECT_NAME: "cloudos-cli-tests"
        WORKFLOW: "GH-rnatoy"
        JOB_CONFIG: "cloudos_cli/examples/rnatoy.config"
        JOB_NAME_BASE: "cloudos-cli-CI-test"
        COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
        PR_NUMBER: ${{ github.event.number }}
        INSTANCE_TYPE: "c5.large"
      run: |
        JOB_NAME="$JOB_NAME_BASE""|GitHubCommit:""${COMMIT_HASH:0:6}""|PR-NUMBER:""$PR_NUMBER"
        cloudos job run --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --workspace-id $CLOUDOS_WORKSPACE_ID --project-name "$PROJECT_NAME" --workflow-name "$WORKFLOW" --job-config $JOB_CONFIG --job-name "$JOB_NAME" --wait-completion --instance-type $INSTANCE_TYPE 2>&1 | tee out.txt
        JOB_ID=$(grep -e "Your assigned job id is:" out.txt | rev | cut -f1 -d " " | rev)
        echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT
        cloudos job status --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --job-id $JOB_ID
  logs_results_aws:
    needs: job_run_and_status
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
        feature: ["logs", "results"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Run tests
        env:
          CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
          CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
          CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          cloudos job ${{ matrix.feature }} --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --workspace-id $CLOUDOS_WORKSPACE_ID --job-id ${{ needs.job_run_and_status.outputs.job_id }}
  workflow_list:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      env:
        CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
        CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
        CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
      run: |
        cloudos workflow list --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --workspace-id $CLOUDOS_WORKSPACE_ID
  project_list:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      env:
        CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
        CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
        CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
      run: |
        cloudos project list --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --workspace-id $CLOUDOS_WORKSPACE_ID
  queue_list:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      env:
        CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
        CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
        CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
      run: |
        cloudos queue list --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --workspace-id $CLOUDOS_WORKSPACE_ID
  dataset_list:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      env:
        CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
        CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
        PROJECT_NAME: "cloudos-cli-tests"
        CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
      run: |
        cloudos datasets ls --cloudos-url $CLOUDOS_URL --apikey $CLOUDOS_TOKEN --workspace-id $CLOUDOS_WORKSPACE_ID --project-name "$PROJECT_NAME" 
  dataset_move:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      env:
        CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
        CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
        PROJECT_NAME: "cloudos-cli-tests"
        CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
      run: |
        cloudos datasets mv --cloudos-url "$CLOUDOS_URL" --apikey "$CLOUDOS_TOKEN" --workspace-id "$CLOUDOS_WORKSPACE_ID" --project-name lm-test Data/test_mv/test_file.txt --destination-project-name "$PROJECT_NAME"  Data/mv_test 
        cloudos datasets mv --cloudos-url "$CLOUDOS_URL" --apikey "$CLOUDOS_TOKEN" --workspace-id "$CLOUDOS_WORKSPACE_ID" --project-name "$PROJECT_NAME" Data/mv_test/test_file.txt --destination-project-name lm-test Data/test_mv
  dataset_rename:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run tests
      env:
        CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
        CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
        PROJECT_NAME: "cloudos-cli-tests"
        CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
      run: |
        cloudos datasets rename --cloudos-url "$CLOUDOS_URL" --apikey "$CLOUDOS_TOKEN" --workspace-id "$CLOUDOS_WORKSPACE_ID" --project-name "$PROJECT_NAME" Data/test_rename new_renamed_folder
        cloudos datasets rename --cloudos-url "$CLOUDOS_URL" --apikey "$CLOUDOS_TOKEN" --workspace-id "$CLOUDOS_WORKSPACE_ID" --project-name "$PROJECT_NAME" Data/new_renamed_folder test_rename
  dataset_copy_and_remove:
          runs-on: ubuntu-latest
          strategy:
            matrix:
              python-version: ["3.9"]
          steps:
          - uses: actions/checkout@v3
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
              cache: pip
              cache-dependency-path: setup.py
          - name: Install dependencies
            run: |
              pip install -e .
          - name: Run tests
            env:
              CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
              CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
              PROJECT_NAME: "cloudos-cli-tests"
              CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
            run: |
              cloudos datasets cp --cloudos-url "$CLOUDOS_URL" --apikey "$CLOUDOS_TOKEN" --workspace-id "$CLOUDOS_WORKSPACE_ID" --project-name "$PROJECT_NAME" Data/mv_test/test_file.txt Data/test_rename 
              cloudos datasets rm --cloudos-url "$CLOUDOS_URL" --apikey "$CLOUDOS_TOKEN" --workspace-id "$CLOUDOS_WORKSPACE_ID" --project-name "$PROJECT_NAME" Data/mv_test/test_file.txt
  dataset_mkdir_and_remove:
                runs-on: ubuntu-latest
                strategy:
                  matrix:
                    python-version: ["3.9"]
                steps:
                - uses: actions/checkout@v3
                - name: Set up Python ${{ matrix.python-version }}
                  uses: actions/setup-python@v4
                  with:
                    python-version: ${{ matrix.python-version }}
                    cache: pip
                    cache-dependency-path: setup.py
                - name: Install dependencies
                  run: |
                    pip install -e .
                - name: Run tests
                  env:
                    CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
                    CLOUDOS_WORKSPACE_ID: ${{ secrets.CLOUDOS_WORKSPACE_ID }}
                    PROJECT_NAME: "cloudos-cli-tests"
                    CLOUDOS_URL: "https://stg.sdlc.lifebit.ai"
                  run: |
                    cloudos datasets mkdir --cloudos-url "$CLOUDOS_URL" --apikey "$CLOUDOS_TOKEN" --workspace-id "$CLOUDOS_WORKSPACE_ID" --project-name "$PROJECT_NAME" Data/to_remove
                    cloudos datasets rm --cloudos-url "$CLOUDOS_URL" --apikey "$CLOUDOS_TOKEN" --workspace-id "$CLOUDOS_WORKSPACE_ID" --project-name "$PROJECT_NAME" Data/to_remove